// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/robertaparri/Developer/raparri01/NEAR-Hackathon/nft-analytics-frontend/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/robertaparri/Developer/raparri01/NEAR-Hackathon/nft-analytics-frontend/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/robertaparri/Developer/raparri01/NEAR-Hackathon/nft-analytics-frontend/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
}
