// This file was generated by RedwoodJS
import { RouteParams, QueryParams } from '@redwoodjs/router'
import { A } from 'ts-toolbelt'


declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    app: (params?: RouteParams<"/{appName:String}"> & QueryParams) => "/{appName:String}"
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
  }
}

